### ISSUE TITLE
Restangular collection custom method polling issue

### ISSUE THREAD

**Issue by simonasdev** [emmaguo/angular-poller#20]
Hello. I have made angular-poller work with plain $http string, but when I tried to switch to Restangular, I have encountered an issue. Basically when the app runs, first request is sent successfully, but any request, that should occur after the interval, is not being sent, even though notifyCallback is being triggered with the same, as after the initial request, Restangular object as an argument. I am using a custom Restangular method, so maybe that is the problem? Here's my setup:
```javascript
// config
RestangularProvider.addElementTransformer('users', true, function (users) {
    users.addRestangularMethod('notifications', 'get', 'notifications');
    return users;
});
// controller
notificationPoller = poller.get(Restangular.all('users'), {
    action: 'notifications',
    delay: 60000,
    smart: true
});
notificationPoller.promise.then(null, null, function (response) {
    // response is a Restangular object with a property notifications which should contain data received from the server
    $rootScope.currentUser.notifications = response.notifications;
});
```
As I mentioned, when I reload the page, the first request is being sent successfully. After that notifyCallback is triggered without sending a request, so argument(response) passed in is the same. Does angular-poller support custom methods for collections? Any insights would be appreciated.

**Comment by emmaguo** [comment]
Hi @simonasdev, angular-poller does support custom methods for restangular collections, and the code you posted looks fine to me. The notifyCallback should not be triggered at all if there is no new request. Is it possible that you were sending requests every 60 seconds but the server response stayed the same? Can you double check your network tab?

**Comment by simonasdev** [comment]
I double checked both server logs and network tab, requests were not being sent. It seems that the issue was in another place. In my config block, I had also set `RestangularProvider.setDefaultHttpFields({ cache: true });`. When I commented out this line, requests started polling correctly as expected. I don't want to disable cache for whole app, so it would be great to be able set defaultHttpFields in the angular-poller, if it is possible.

**Comment by emmaguo** [comment]
Restangular does not support caching for specific request. It would be a lot easier if it supports something like `addRestangularMethod(name, operation, [path, params, headers, config, elem])`... To me it does not make much sense to add `defaultHttpFields` or a `cache` field to angular-poller simply because you can already pass in `cache` as part of the `argumentsArray` to `$http` and `$resource` requests.

But you can still fix your issue without disabling cache for the whole app.

Solution1:
```javascript
RestangularProvider.setFullRequestInterceptor(function(element, operation, route, url, headers, params, httpConfig) {
  if (operation === 'get' && url === 'notifications') {
    httpConfig.cache = false;
  }
  return {
    httpConfig: httpConfig
  };
});
```

Solution2:
```javascript
myapp.factory('RestangularNoCache', function(Restangular) {
  return Restangular.withConfig(function(RestangularProvider) {
    RestangularProvider.setDefaultHttpFields({cache: false});
  });
});

// controller
notificationPoller = poller.get(RestangularNoCache.all('users'), {
    action: 'notifications',
    delay: 60000,
    smart: true
});
```

Let me know if that helps!

**Comment by simonasdev** [comment]
Oh. I see. Thanks for your solutions, I chose the the first one, although it needed a little bit of tweaking. Here's the final version (notice that the method should be `addFullRequestInterceptor`):
```javascript
RestangularProvider.addFullRequestInterceptor(function (element, operation, route, url, headers, params, httpConfig) {
    if (operation === 'get' && route === 'notifications') {
      httpConfig.cache = false;
    }
    return {
      httpConfig: httpConfig
    };
});
```
It is working as expected. I must have overlooked this method in the docs earlier. Thanks for making this world a better place
