### ISSUE TITLE
Init poller withouth start it

### ISSUE THREAD

**Issue by zazasa** [emmaguo/angular-poller#21]
Hi, is it possible to initialize a poller withouth starts it?
I need to create a function that start or restart the poller in this way:

```javascript
    runRanger.start = function(){
        mypoller = poller.get(resource, {
            action: 'jsonp_get',
            delay: config.fastPollingDelay,
            smart: true,
            argumentsArray:[{sysName:indexListService.selected.subSystem,size:1}]
        });       
        mypoller.promise.then(null, null, function(data) {
            console.log(data);
        })
    };
```

But if i call mypoller.stop() and then runRanger.start(), the promise is triggered twice.

but if i do this way:

```javascript
        mypoller = poller.get(resource, {
            action: 'jsonp_get',
            delay: config.fastPollingDelay,
            smart: true,
            argumentsArray:[{sysName:indexListService.selected.subSystem,size:1}]
        });       
        mypoller.promise.then(null, null, function(data) {
            console.log(data);
        })

    runRanger.start = function(){
        mypoller = poller.get(resource, {
            argumentsArray:[{sysName:indexListService.selected.subSystem,size:1}]
        });       
    };
```

it works, but it starts the poller before i call runRanger.start() the first time, i guess the issue is trying to overwrite the promise.
I need to use this function when i change the argumentsArray.
I also tried to add a mypoller.stop() just after the definition but sometimes it starts anyway.

**Comment by emmaguo** [comment]
Hi @zazasa you cannot call `poller.get` without starting the poller.
But you can totally modify your `runRanger.start` like so:
```javascript
runRanger.start = function(){
  if (angular.isUndefined(myPoller)) {
    // Initialize poller and its callback
    mypoller = poller.get(resource, {
      action: 'jsonp_get',
      delay: config.fastPollingDelay,
      smart: true,
      argumentsArray:[{sysName:indexListService.selected.subSystem,size:1}]
    });       
    mypoller.promise.then(null, null, function(data) {
      console.log(data);
    });
  } else {
    // Restart poller
    mypoller = poller.get(resource, {
      argumentsArray:[{sysName:indexListService.selected.subSystem,size:1}]
    });
  }
};
```

Let me know if that works for you.:-)

**Comment by zazasa** [comment]
Yes, it works like a charm.
You are very kind, and nice job with this lib.

Thank you

**Comment by emmaguo** [comment]
Thanks!!

**Comment by nicolaib** [comment]
It would be a great change and would really complete the package, if there was a way to delay the first request with the same or a different timeout as the poll interval. Setting a timeout before it's registered means that the instance is not available for e.g. destruction on leaving the scope where it is applied. I hope this will be a consideration. Thanks for an awesome package 😃
