### ISSUE TITLE
Allow passing functions as arguments, and evaluate them on every tick.

### ISSUE THREAD

**Issue by cur3n4** [emmaguo/angular-poller#22]
Hello, 
It would be nice to be able to support passing functions in the arguments array, so that they are evaluated everytime a request is made to the backend.
Or maybe there is a solution already?
Cheers

**Comment by emmaguo** [comment]
You can use the `notifyCallback` everytime you get a response from backend, or use `interceptors` to intercept request before sending it to the backend. Does that help? What is your use case?

**Comment by cur3n4** [comment]
The use case is a user filling a survey, and the responses being sent to the backend every 10 seconds. Ideally I would like to pass a function which determines the right responses to send and that it is executed when the poller ticks, and not just once when the poller gets created. The notifyCallback is probably not enough, interceptors are and option, but I don't think the solution would be very nice. 
The modification to the tick version could be in very rough terms something like:


    var argumentsArrayForTick = argumentsArray.slice();
    if (argumentsArrayForTick.length == 2 && typeof (argumentsArrayForTick[1]) == 'function') {
        argumentsArrayForTick[1] = argumentsArrayForTick[1]();
    }
    timestamp = new Date();
    current = target[action].apply(self, argumentsArrayForTick);

**Comment by emmaguo** [comment]
@cur3n4 I do not think that is a common use case, so am not going to support this for now. But please feel free to fork it. Also instead of using a poller, you can send the survey response to backend every time when user clicks on a next button or focus on an input field etc.

**Comment by emmaguo** [comment]
Closed for now. Will reopen if there are similar requests in the future.

**Comment by emmaguo** [comment]
Reopened issue to support dynamic argumentsArray. :-)

**Comment by cur3n4** [comment]
My interim solution is as follows:

    var customTarget = {
        post: function(url, functionToExecute) {
            return $http.post(url, functionToExecute());
        }
    };
    var thePoller = poller.get(customTarget, {
         action: 'post',
         argumentsArray: [
             aUrl, aFunction
         ],
    });

**Comment by goldenram** [comment]
Hi,  Is there any update on supporting updating the argumentsArray while the poller is running?  My use case is while the poller is running and updating, a user may set some filter params or change the sorting of the grid and we need to send this info to the server and will get back an updated list of items that match the filter.

**Comment by bentobecker** [comment]
Yes, I have the exact same use case! It would be great if updating the argumentsArray could be added.

**Comment by m-gv** [comment]
I have the same use case as well.

**Comment by emmaguo** [comment]
Sorry for the delay. 
It's implemented now in v0.4.3. 🎉 
https://github.com/emmaguo/angular-poller#update-argumentsarray-while-poller-is-running
