### ISSUE TITLE
Multi pollers, stop specific one when state changed, not "stopAll"

### ISSUE THREAD

**Issue by ramsaylee** [emmaguo/angular-poller#27]
Hi Emma,

First of all, thanks for this great module, nice job!

Here is the situation, I have two pollers: poller-A for all pages and poller-B for only one page. I just want poller-B only work in the specific page, so I use "pollerConfig.stopOnStateChange = true" to stop it when state changed, but this will stop all pollers while I want to keep poller-A still working.

Is there anything I can do to implement this? Coule you please help? 

Thanks again,
Lee

**Comment by emmaguo** [comment]
Hi @ramsaylee 
`pollerConfig.stopOnStateChange` is really for all pollers. In your case, instead of using `pollerConfig`, you can use the following in your controller:
```javascript
$scope.$on('$stateChangeStart', function () {
  pollerB.stop(); 
});
```
I hope that helps. :-)
