### ISSUE TITLE
ui-router resolve?

### ISSUE THREAD

**Issue by jondthompson** [emmaguo/angular-poller#28]
Is there support for ui-router's resolve? Something where we could $watch the promise and update using normal angular methods?

**Comment by emmaguo** [comment]
Hi @jondthompson I'm guessing you want to use poller in `resolve` so that you get at least one success notifyCallback before the controller is instantiated. If that is the case, you can use:
```javascript
$stateProvider.state('myState', {
  resolve: {
    myData: function($q, poller, myResource){
      var deferred = $q.defer();
      poller.get(myResource).promise.then(null, null, function(data){
        deferred.resolve(data);
      });
      return deferred.promise;
    }
  }
});
```
I hope that helps. :)
