### ISSUE TITLE
Poller breaks on minification

### ISSUE THREAD

**Issue by AnimaLupi** [emmaguo/angular-poller#31]
Hello,

when using minification the dependency injection fails.

It could be easily fixed by using the inline annotation, I tried making a pull request (did the fix directly online in github, so hopefully I placed the closing square brakets in the right places :-)

https://github.com/emmaguo/angular-poller/pull/30

Hope it can be used, ciao!

**Comment by jdcaballerov** [comment]
When using a minified version from cdnjs there is no problem. Take a look.
https://cdnjs.cloudflare.com/ajax/libs/angular-poller/0.3.2/angular-poller.min.js

**Comment by AnimaLupi** [comment]
I was using the non-minified version and minifying it myself as I'm using Grunt to perform minification (uglify and mangling to be precise, the latter being the issue as it changes variables names).
Having an annotated injection version could avoid treating this module as a special case in the Grunt chain (I'm lazy, I know :-) ) and also permit the use of the mangling option (to reduce size even more than the non-mangled version).
That being said, thanks for the hint!

**Comment by justingrayston** [comment]
If you plumb in [ngAnnotate](https://github.com/mzgol/grunt-ng-annotate) before you uglify you should be ok. This places the dependencies in the array notation etc...

**Comment by AnimaLupi** [comment]
@justingrayston Thanks, I'll surely end up using ngAnnotate (even if in the beginning I was trying to avoid using that).

My project uses several external modules with the uglify issue due to services declaration syntax and in fact it seems it would take more effort to fork and get pull requests integrated than simply set up ngAnnotate to fix the problem :-)

**Comment by emmaguo** [comment]
@AnimaLupi: Merged. Thanks for the PR!:-)
