### ISSUE TITLE
Multiple Pollers Cause Blocking

### ISSUE THREAD

**Issue by tysonnero** [emmaguo/angular-poller#4]
I'm running into an issue that when I have two pollers, I am noticed blocking that increases over time when trying to execute other code such as unrelated $http calls.

I haven't had time to create a fiddle yet as my use case is a little complex, however, I've already made the fix to the angular-poller library locally that alleviates. I've forked the repo and will initiate a pull request once checked in.

**Comment by JamesHaskell** [comment]
Thanks for this great work!  I'm a bit of an Angular newbie, so please forgive me if the answer to this is obvious... I want to do an incremental retrieve of new alerts in my DB... so I need to do retrieves like:
url/messages/after/:id
where "id" changes each cycle (it will be the max retrieved on the previous cycle).  Is that possible?  I tried something like:
var myPoller = poller.get(pollerResource, {
...
argumentsArray: [{id: maxCurrentDataID}]
}
but the id sent in the url was zero.  Using a static value (argumentsArray: [{id: 330}]) did work OK...  

Thanks again... your module has been a big help to me.

**Comment by emmaguo** [comment]
Hi @JamesHaskell 
Currently it is not possible to pass in dynamic argumentsArray to angular poller. However @cur3n4 raised a similar issue before. I will reopen https://github.com/emmaguo/angular-poller/issues/22 and address it over there.:)

**Comment by JamesHaskell** [comment]
Don't know if this will help you, but I got it to work for me with the following (note: unusual $scope / Controller As syntax due to issues with the ng-grid control):


(function () {
    'use strict';

    angular
        .module('commStatusApp')
        .controller('AlertsController', AlertsController);

    AlertsController.$inject = ['$scope', '$resource', 'poller', 'alertsGridSettings'];

    function AlertsController($scope, $resource, poller, alertsGridSettings) {
        /* jshint validthis: true */
        var vm = this;
        var maxCurrentDataID = 0;

        $scope.currentData = [];

        vm.alertsGridOptions = alertsGridSettings['default'];
        vm.alertsSelections = [];
        vm.alertsGridOptions['selectedItems'] = vm.alertsSelections;

        var AlertsResource = $resource("/alerts/after/:id", {id: '@id'}, {
            getStatuses: {
                method: 'GET',
                isArray: true
            }
        });
        var myPoller = poller.get(AlertsResource, {
            action: 'getStatuses',
            delay: 11000,
            smart: false,
            argumentsArray: [
                { id: maxCurrentDataID }
            ]
        });
        myPoller.promise.then(null, null, function (data) {
            storeData(data);
        });

        function storeData(newData) {
            $scope.currentData = newData.concat($scope.currentData);
            $scope.currentData.splice(20, 99);
            maxCurrentDataID = Math.max.apply(Math, $scope.currentData.map(function(o){return o.id;}));
            myPoller.argumentsArray[0].id = maxCurrentDataID;
        }
    }
})();

**Comment by emmaguo** [comment]
@JamesHaskell I'm glad you found a workaround. That's awesome! I'll include a way to pass in dynamic argumentsArray in the next version.
