### ISSUE TITLE
Multiple request at same time and smart config it's true

### ISSUE THREAD

**Issue by vitornobrega** [emmaguo/angular-poller#45]
I had smart with true value in poller config and sometimes i see in browser request, 2 or 3 pending requests at the same time. When requests gives timeout , are again started.This should not be avoided with the option smart : true?

I need to change something to only send new request if the previous one is resolved?

**Comment by emmaguo** [comment]
Hi @vitornobrega 
If you are using `pollerConfig.smart = true;` you really should not see multiple pending requests to the same resource at the same time. I'm guessing you have multiple pollers to different resources running at the same time.
`smart` flag only makes sure that new requests are sent after the previous on is resolved - and that could mean success or failure. If you want to handle the timeout case, you can take a look at https://github.com/emmaguo/angular-poller#error-handling.
Let me know if you have more questions.
