### ISSUE TITLE
Where are the change logs?

### ISSUE THREAD

**Issue by moneytree-doug** [emmaguo/angular-poller#47]
I can't seem to find out what's in 0.3.4 and if I should upgrade.

**Comment by emmaguo** [comment]
@moneytree-doug: 
Here is the change log: https://github.com/emmaguo/angular-poller/compare/v0.3.3...v0.3.4
The main changes are newly added `pollerConfig.smart` and `poller.remove()`. It is backward compatible with `v0.3.3`.

I will start adding release notes for future releases.
