### ISSUE TITLE
Poller does not stop on $stateChangeStart

### ISSUE THREAD

**Issue by alereisan** [emmaguo/angular-poller#51]
I am using the poller like this in the controller:

```
var productViewPoller = poller.get('/products/' + $stateParams.id + '.json', { delay: 10000, smart: true, idleDelay: 60000});

productViewPoller.promise.then(null, null, function(resp) {
  $scope.product.bids = angular.copy(resp.data.bids);
  $scope.product.questions = angular.copy(resp.data.questions);
});

// Stop Poller if user changes $state URL
$scope.$on('$stateChangeStart', function (){
  console.log("View closed");
  productViewPoller.stop();
});
```

I see "View closed" in the console, when I leave / change the $state, but the poller does not stop and keeps running.

**Comment by alereisan** [comment]
This problem appears when using ```pollerConfig.handleVisibilityChange = true;```

Is there anyway to config the poller to slow down on visibility change, while still stopping on state change?

**Comment by emmaguo** [comment]
@alereisan Good catch! Fix is on the way 🎉

**Comment by emmaguo** [comment]
https://github.com/emmaguo/angular-poller/releases/tag/v0.4.4
