### ISSUE TITLE
Support $interval count param

### ISSUE THREAD

**Issue by goldenram** [emmaguo/angular-poller#55]
If I only need to run the poller a single time, right now I have to stop the poller inside the promise.  It would be great if we can pass in a param, like count, which could be passed to the underlying $interval the poller code is using telling it to run a number of times.

**Comment by emmaguo** [comment]
If you only need to run it a single time, you can just use `$resource`, `$http`, or `restangular` directly without poller.

**Comment by goldenram** [comment]
Agreed, I was just hoping to avoid have to conditionally branch code and add in a bunch of extra checks.
