### ISSUE TITLE
`target` instead of `self`

### ISSUE THREAD

**Issue by moneytree-doug** [emmaguo/angular-poller#56]
https://github.com/emmaguo/angular-poller/blob/27d46ed9edbd9a0f4e5a81202a6093ed8bbd0bf5/angular-poller.js#L251

```
current =
                                target[action].apply(self, argumentsArray);
```

If you are running ``apply`` here then it makes sense to always use the target for context to run with itself, so then the `this` context doesn't change. In my case, I have helpers wrapped around my `$http` and `$resource` , and it's trying to access `this` which is the poller object.

Proposed change:
```
current =
                                target[action].apply(target, argumentsArray);
```

Thoughts before I make a PR?

**Comment by emmaguo** [comment]
Makes total sense. Please feel free to make a PR. Thanks!

**Comment by moneytree-doug** [comment]
@emmaguo I submitted a PR (#57)

**Comment by emmaguo** [comment]
@moneytree-doug thanks for the PR. Already merged it into master, will have a new release out soon.

**Comment by moneytree-doug** [comment]
@emmaguo Awesome, thanks!
